Refactor SnippetHelper
WGBH-MLA/AAPB2 pull request #2291
Opened 2021-07-29 20:00 UTC by foglabs

-Refactors SnippetHelper into TimecodeSnippet and Snippet classes
-Refactors `query_for_captions` method to separate concerns
-Moves snippet specs from `caption_file_spec` into snippet spec
-Deletes old specs from `transcript_file_spec`
-Expands `snippet_helper_spec` a little
-Caches stopwords.txt file instead of always loading

2021-09-15 19:03 UTC, afred requested changes

2021-09-15 19:03 UTC, afred commented on app/controllers/catalog_controller.rb
> +    @terms_array = query_to_terms_array(query) if query
@foglabs I think that if `query` is `nil` here, then `@terms_array` will be `nil`, and then the 2nd param to `Snippet#initialize` will be nil, and then calling `Snippet#snippet` will raise a `NoMethodError #each for Nil:Class` when trying to iterate of `@terms_array`.

If `clean_query_for_snippet` should always return an array, then I'd suggest adding a guard clause to it, and then get rid of the `if query` conditional on line 198. E.g.
```
# in CatalogController
def index
  # ...
  @terms_array = query_to_terms_array(query)
  # ...
end

# in ApplicationHelper
def query_to_terms_array(query)
  return [] if query.empty?
  #...
end
```

2021-09-15 20:02 UTC, foglabs commented on app/controllers/catalog_controller.rb
> +    @terms_array = query_to_terms_array(query) if query
👍

2021-09-22 19:48 UTC, afred approved these changes
👍 - confirmed specs passing with @foglabs via Slack.

2021-09-22 19:48 UTC, merged